This is a Cloud Foundry Firehose Nozzle written using https://github.com/cloudfoundry/cf-java-client[CF-Java-Client] and Spring Boot. This project is heavily inspired by
https://github.com/cloudfoundry-community/firehose-to-syslog[go based firehose-to-syslog] nozzle and should be completely feature compatible with that project including being able to enhance log details with information about application name.

== Developing Locally

* Clone this project
[source]
....
git clone https://github.com/bijukunjummen/boot-firehose-to-syslog
....

* Build it locally
[source]
....
./gradlew clean build
....

* Run it locally
[source]
....
./gradlew bootRun
....

If you have a local PCF Dev available you should see logs being printed to the console at this point.

== Deploying the Nozzle

* Specify the parameters to Splunk using the manifest file or by setting the environment variables:
[source]
----
      cf_host: api.local.pcfdev.io
      cf_user: admin
      cf_password: admin
      cf_skip_ssl_validation: true
      firehose_event_types: LogMessage, ValueMetric, ContainerMetric
      firehose_text_format: SPLUNK
      firehose_parallelism: 5
      syslog_server: asyslogserver
      syslog_port: 9997
      syslog_connection_type: TCP
----

The text format can be set to SPLUNK or JSON, the eventTypes to HttpStart, HttpStop, HttpStartStop, LogMessage, ValueMetric,  CounterEvent,  Error, ContainerMetric

Metrics can be sent over both TCP/UDP. If the connectionType is set to "DEBUG" then the logs will simply be printed to the console which is the default mode.

* Push the app once you have a working set of environment variables in the manifest file:
[source]
----
cf push
----






