cf:
  host: api.local.pcfdev.io
  user: admin
  password: admin
  skipSslValidation: true

firehose:
  eventTypes: LOG_MESSAGE
  textFormat: TEXT
  parallelism: 5
  subscriptionId: boot-firehose-to-syslog

#syslog:
#  connectionType: TCP # OR UDP OR DEBUG
#  server: splunkServer
#  port: 9997
# CONTAINER_METRIC,COUNTER_EVENT,ERROR,HTTP_START_STOP,LOG_MESSAGE,VALUE_METRIC

logging:
  level:
    root: INFO
    io.netty: INFO
    reactor.ipc.netty: INFO
    io.pivotal.cf.nozzle.syslog.DebuggingSyslogSender: DEBUG
    cloudfoundry-client.response: DEBUG
    cloudfoundry-client.request: DEBUG